# Docker Compose의 버전 (https://docs.docker.com/compose/compose-file/)
version: "3.8"

x-datanode_base: &datanode_base
  image: hadoop-datanode:3.1.1
  networks:
    - bridge

#각 컨테이너에 사용할 이미지와 포트, 볼륨 정보를 정의
services:
  namenode:
    image: hadoop-namenode:3.1.1
    container_name: namenode
    hostname: public host
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - /tmp:/tmp
    networks:
      - bridge
  datanode01:
    <<: *datanode_base
    container_name: datanode01
    hostname: public host
    volumes:
      - datanode01:/opt/hadoop/dfs/data
  datanode02:
    <<: *datanode_base
    container_name: datanode02
    hostname: public host
    volumes:
      - datanode02:/opt/hadoop/dfs/data
volumes:
  namenode:
  datanode01:
  datanode02:
networks:
  bridge:

